// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolBuffer.proto

package com.why.tool.proto;

public final class ProtocolBuffer {
  private ProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ByteListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated bytes elements = 1;
    java.util.List<com.google.protobuf.ByteString> getElementsList();
    int getElementsCount();
    com.google.protobuf.ByteString getElements(int index);
  }
  public static final class ByteList extends
      com.google.protobuf.GeneratedMessage
      implements ByteListOrBuilder {
    // Use ByteList.newBuilder() to construct.
    private ByteList(Builder builder) {
      super(builder);
    }
    private ByteList(boolean noInit) {}
    
    private static final ByteList defaultInstance;
    public static ByteList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ByteList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.why.tool.proto.ProtocolBuffer.internal_static_ByteList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.why.tool.proto.ProtocolBuffer.internal_static_ByteList_fieldAccessorTable;
    }
    
    // repeated bytes elements = 1;
    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> elements_;
    public java.util.List<com.google.protobuf.ByteString>
        getElementsList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public com.google.protobuf.ByteString getElements(int index) {
      return elements_.get(index);
    }
    
    private void initFields() {
      elements_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < elements_.size(); i++) {
        output.writeBytes(1, elements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < elements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(elements_.get(i));
        }
        size += dataSize;
        size += 1 * getElementsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.ByteList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.why.tool.proto.ProtocolBuffer.ByteList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.why.tool.proto.ProtocolBuffer.ByteListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.why.tool.proto.ProtocolBuffer.internal_static_ByteList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.why.tool.proto.ProtocolBuffer.internal_static_ByteList_fieldAccessorTable;
      }
      
      // Construct using com.why.tool.proto.ProtocolBuffer.ByteList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.why.tool.proto.ProtocolBuffer.ByteList.getDescriptor();
      }
      
      public com.why.tool.proto.ProtocolBuffer.ByteList getDefaultInstanceForType() {
        return com.why.tool.proto.ProtocolBuffer.ByteList.getDefaultInstance();
      }
      
      public com.why.tool.proto.ProtocolBuffer.ByteList build() {
        com.why.tool.proto.ProtocolBuffer.ByteList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.why.tool.proto.ProtocolBuffer.ByteList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.why.tool.proto.ProtocolBuffer.ByteList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.why.tool.proto.ProtocolBuffer.ByteList buildPartial() {
        com.why.tool.proto.ProtocolBuffer.ByteList result = new com.why.tool.proto.ProtocolBuffer.ByteList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.why.tool.proto.ProtocolBuffer.ByteList) {
          return mergeFrom((com.why.tool.proto.ProtocolBuffer.ByteList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.why.tool.proto.ProtocolBuffer.ByteList other) {
        if (other == com.why.tool.proto.ProtocolBuffer.ByteList.getDefaultInstance()) return this;
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureElementsIsMutable();
              elements_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated bytes elements = 1;
      private java.util.List<com.google.protobuf.ByteString> elements_ = java.util.Collections.emptyList();;
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new java.util.ArrayList<com.google.protobuf.ByteString>(elements_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getElementsList() {
        return java.util.Collections.unmodifiableList(elements_);
      }
      public int getElementsCount() {
        return elements_.size();
      }
      public com.google.protobuf.ByteString getElements(int index) {
        return elements_.get(index);
      }
      public Builder setElements(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addElements(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
        return this;
      }
      public Builder clearElements() {
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ByteList)
    }
    
    static {
      defaultInstance = new ByteList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ByteList)
  }
  
  public interface IntListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int32 elements = 1;
    java.util.List<java.lang.Integer> getElementsList();
    int getElementsCount();
    int getElements(int index);
  }
  public static final class IntList extends
      com.google.protobuf.GeneratedMessage
      implements IntListOrBuilder {
    // Use IntList.newBuilder() to construct.
    private IntList(Builder builder) {
      super(builder);
    }
    private IntList(boolean noInit) {}
    
    private static final IntList defaultInstance;
    public static IntList getDefaultInstance() {
      return defaultInstance;
    }
    
    public IntList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.why.tool.proto.ProtocolBuffer.internal_static_IntList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.why.tool.proto.ProtocolBuffer.internal_static_IntList_fieldAccessorTable;
    }
    
    // repeated int32 elements = 1;
    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> elements_;
    public java.util.List<java.lang.Integer>
        getElementsList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public int getElements(int index) {
      return elements_.get(index);
    }
    
    private void initFields() {
      elements_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < elements_.size(); i++) {
        output.writeInt32(1, elements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < elements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(elements_.get(i));
        }
        size += dataSize;
        size += 1 * getElementsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.why.tool.proto.ProtocolBuffer.IntList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.why.tool.proto.ProtocolBuffer.IntList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.why.tool.proto.ProtocolBuffer.IntListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.why.tool.proto.ProtocolBuffer.internal_static_IntList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.why.tool.proto.ProtocolBuffer.internal_static_IntList_fieldAccessorTable;
      }
      
      // Construct using com.why.tool.proto.ProtocolBuffer.IntList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.why.tool.proto.ProtocolBuffer.IntList.getDescriptor();
      }
      
      public com.why.tool.proto.ProtocolBuffer.IntList getDefaultInstanceForType() {
        return com.why.tool.proto.ProtocolBuffer.IntList.getDefaultInstance();
      }
      
      public com.why.tool.proto.ProtocolBuffer.IntList build() {
        com.why.tool.proto.ProtocolBuffer.IntList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.why.tool.proto.ProtocolBuffer.IntList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.why.tool.proto.ProtocolBuffer.IntList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.why.tool.proto.ProtocolBuffer.IntList buildPartial() {
        com.why.tool.proto.ProtocolBuffer.IntList result = new com.why.tool.proto.ProtocolBuffer.IntList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.why.tool.proto.ProtocolBuffer.IntList) {
          return mergeFrom((com.why.tool.proto.ProtocolBuffer.IntList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.why.tool.proto.ProtocolBuffer.IntList other) {
        if (other == com.why.tool.proto.ProtocolBuffer.IntList.getDefaultInstance()) return this;
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureElementsIsMutable();
              elements_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addElements(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 elements = 1;
      private java.util.List<java.lang.Integer> elements_ = java.util.Collections.emptyList();;
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new java.util.ArrayList<java.lang.Integer>(elements_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getElementsList() {
        return java.util.Collections.unmodifiableList(elements_);
      }
      public int getElementsCount() {
        return elements_.size();
      }
      public int getElements(int index) {
        return elements_.get(index);
      }
      public Builder setElements(
          int index, int value) {
        ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addElements(int value) {
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
        return this;
      }
      public Builder clearElements() {
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:IntList)
    }
    
    static {
      defaultInstance = new IntList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:IntList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ByteList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ByteList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IntList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IntList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProtocolBuffer.proto\"\034\n\010ByteList\022\020\n\010el" +
      "ements\030\001 \003(\014\"\033\n\007IntList\022\020\n\010elements\030\001 \003(" +
      "\005B\024\n\022com.why.tool.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ByteList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ByteList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ByteList_descriptor,
              new java.lang.String[] { "Elements", },
              com.why.tool.proto.ProtocolBuffer.ByteList.class,
              com.why.tool.proto.ProtocolBuffer.ByteList.Builder.class);
          internal_static_IntList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_IntList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IntList_descriptor,
              new java.lang.String[] { "Elements", },
              com.why.tool.proto.ProtocolBuffer.IntList.class,
              com.why.tool.proto.ProtocolBuffer.IntList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
